import {useEffect,useState} from "react";
import {api} from "../../../services/apiService";
import {dinero,fechaTexto,mensajeError} from "../../../services/gestionService";
import {fechaLocal} from "../../../types/evento";
import type {ReporteFinanciero,ReporteOperativo,PaginaMermaReporte} from "../../../types/reporte";
import PeriodoReportes from "../../../components/shared/PeriodoReportes";
import type {FiltroReporte} from "../../../components/shared/PeriodoReportes";
import Ranking from "./Ranking";

const nombres={PEDIDOS:"Pedidos de flores",ARREGLOS:"Arreglos",EVENTOS:"Eventos"};
const secciones=[['resumen','Ingresos y balance','cash-stack'],['flores','Flores y merma','flower3'],['clientes','Clientes y arreglos','people'],['compras','Compras y proveedores','truck']] as const;
export default function IndexReportes() {
  const [filtro,setFiltro]=useState<FiltroReporte>(()=>({periodo:"MES",fecha:fechaLocal(new Date())})),[seccion,setSeccion]=useState("resumen"),[revision,setRevision]=useState(0),[pagina,setPagina]=useState(0),[tamano,setTamano]=useState(10);
  const [resultado,setResultado]=useState<{clave:string;finanzas?:ReporteFinanciero;operativos?:ReporteOperativo;error?:string}>({clave:""});
  const [mermas,setMermas]=useState<{clave:string;data?:PaginaMermaReporte;error?:string}>({clave:""});
  const [exportando,setExportando]=useState(false),[errorExportacion,setErrorExportacion]=useState("");
  const clave=JSON.stringify([filtro,revision]),claveMermas=JSON.stringify([filtro,pagina,tamano,revision]);
  useEffect(()=>{const controller=new AbortController();Promise.all([api.get<ReporteFinanciero>("/reporte/financieros",{params:filtro,signal:controller.signal}),api.get<ReporteOperativo>("/reporte/operativos",{params:filtro,signal:controller.signal})]).then(([finanzas,operativos])=>{if(!controller.signal.aborted)setResultado({clave,finanzas:finanzas.data,operativos:operativos.data});}).catch(err=>{if(!controller.signal.aborted)setResultado({clave,error:mensajeError(err)});});return()=>controller.abort();},[filtro,revision,clave]);
  useEffect(()=>{if(seccion!=="flores")return;const controller=new AbortController();api.get<PaginaMermaReporte>("/reporte/mermas/pagina",{params:{...filtro,pagina,tamano},signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted)setMermas({clave:claveMermas,data});}).catch(err=>{if(!controller.signal.aborted)setMermas({clave:claveMermas,error:mensajeError(err)});});return()=>controller.abort();},[filtro,pagina,tamano,revision,claveMermas,seccion]);
  const vigente=resultado.clave===clave,finanzas=vigente?resultado.finanzas:undefined,operativos=vigente?resultado.operativos:undefined,detalle=mermas.clave===claveMermas?mermas.data:undefined;
  const exportar=async(formato:"pdf"|"excel")=>{if(exportando)return;setExportando(true);setErrorExportacion("");try{const [{data},{exportarReportes}]=await Promise.all([api.get("/reporte/exportacion",{params:filtro}),import("../../../services/exportarDocumentos")]);await exportarReportes(data,formato);}catch(e){setErrorExportacion((e as {response?:unknown})?.response?mensajeError(e):e instanceof Error?e.message:mensajeError(e));}finally{setExportando(false);}};
  const recargar=()=>setRevision(r=>r+1);
  const rango=finanzas?.periodo;
  const sinImporte=finanzas?.ingresos.reduce((n,i)=>n+i.sinImporte,0)||0,fechasEstimadas=finanzas?.ingresos.reduce((n,i)=>n+i.fechasEstimadas,0)||0;
  return <section className="fa-management rp-page"><header className="fa-page-heading"><div><p className="fa-eyebrow">FlorArte / Análisis del negocio</p><h1><i className="bi bi-bar-chart-line" aria-hidden="true"/>Reportes</h1><p>Consulta ventas, flores, clientes y compras con los datos de las vistas de la base de datos.</p></div><div className="fa-heading-actions"><button className="fa-button secondary" disabled={exportando||!finanzas||!operativos} onClick={()=>void exportar("pdf")}><i className="bi bi-file-earmark-pdf" aria-hidden="true"/>Exportar PDF</button><button className="fa-button secondary" disabled={exportando||!finanzas||!operativos} onClick={()=>void exportar("excel")}><i className="bi bi-file-earmark-spreadsheet" aria-hidden="true"/>Exportar Excel</button><button className="fa-button secondary" onClick={recargar}><i className="bi bi-arrow-clockwise" aria-hidden="true"/>Actualizar</button></div></header>
    {exportando&&<p className="fa-edit-notice" role="status">Generando archivo con todos los reportes y el detalle completo de merma del período seleccionado…</p>}{errorExportacion&&<p className="fa-alert" role="alert">{errorExportacion}</p>}
    <div className="fa-list-card rp-filters"><PeriodoReportes value={filtro} onChange={nuevo=>{setFiltro(nuevo);setPagina(0);}}/>{rango&&<p className="rp-range" aria-live="polite">Todos los reportes: {fechaTexto(`${rango.desde}T00:00:00`).split(",")[0]} – {fechaTexto(`${rango.hasta}T00:00:00`).split(",")[0]}</p>}</div>
    <nav className="fa-tabs rp-tabs" aria-label="Secciones de reportes">{secciones.map(([value,label,icono])=><button key={value} aria-pressed={seccion===value} className={seccion===value?"active":""} onClick={()=>setSeccion(value)}><i className={`bi bi-${icono}`} aria-hidden="true"/>{label}</button>)}</nav>
    {!vigente?<div className="fa-empty" role="status">Consultando reportes…</div>:resultado.error?<div className="fa-empty"><p role="alert">{resultado.error}</p><button className="fa-button secondary" onClick={recargar}>Reintentar</button></div>:finanzas&&operativos&&<>
      {seccion==="resumen"&&<>
        <div className="fa-metrics rp-metrics">{finanzas.ingresos.map(i=><div key={i.modulo}><span>Ingresos · {nombres[i.modulo]}</span><strong>{dinero(i.importe)}</strong><small>{i.operaciones} operaciones · {i.modulo==="EVENTOS"?"Eventos pagados":"Pedidos entregados"}</small>{!!i.sinImporte&&<small className="rp-missing">{i.sinImporte} sin importe registrado</small>}</div>)}<div className="fa-metric-note"><span>Total de ingresos conocidos</span><strong>{dinero(finanzas.totalIngresos)}</strong><small>Pedidos + arreglos + eventos</small></div></div>
        <div className="fa-metrics"><div><span>Compras de inventario</span><strong>{dinero(finanzas.gastos.importe)}</strong><small>{finanzas.gastos.compras} entradas de proveedores</small></div><div><span>Balance de ventas y compras</span><strong className={finanzas.balance<0?"rp-negative":""}>{dinero(finanzas.balance)}</strong><small>Ingresos conocidos menos compras del período</small></div><div><span>Pérdida por merma con costo conocido</span><strong>{dinero(finanzas.perdidas.importe)}</strong><small>{finanzas.perdidas.unidades} flores desechadas</small></div></div>
        <div className="rp-explanation"><h2>Cómo se leen estas cifras</h2><p>Los ingresos de pedidos y arreglos corresponden a operaciones entregadas, filtradas por la fecha del pedido. Los eventos se incluyen al pagarse, según su fecha de pago.</p><p>El balance compara ventas con compras de inventario. No representa ganancia neta: faltan otros gastos y el costo de las flores vendidas en el período. La merma usa el costo guardado con el registro. Para mermas antiguas sin costo se usa un promedio de compras anteriores.</p>{!!sinImporte&&<p className="fa-alert" role="status">Hay {sinImporte} eventos pagados sin importe. Los ingresos y el balance son parciales; registra los importes desde la edición del evento.</p>}{!!fechasEstimadas&&<p className="fa-edit-notice">{fechasEstimadas} eventos históricos usan la fecha del evento porque no tenían fecha de pago registrada.</p>}{!!finanzas.perdidas.sinCosto&&<p className="fa-alert" role="status">{finanzas.perdidas.sinCosto} registros de merma no tienen costo guardado ni compras anteriores para valorar la pérdida. El total de pérdida es parcial.</p>}</div>
      </>}
      {seccion==="flores"&&<>
        <div className="rp-grid"><Ranking titulo="Flores más demandadas" descripcion="Unidades en pedidos y arreglos entregados, y eventos realizados o pagados. Incluye las flores de cada arreglo." datos={operativos.floresDemandadas} columnas={[{campo:"unidades",titulo:"Flores"}]}/><Ranking titulo="Flores más desechadas" descripcion="Unidades desechadas y pérdida a costo de compra; los registros antiguos pueden usar una referencia estimada." datos={finanzas.floresDesechadas} columnas={[{campo:"unidades",titulo:"Flores"},{campo:"importe",titulo:"Pérdida conocida"}]}/></div>
        <section className="fa-list-card rp-mermas"><header className="rp-card-heading"><div><h2>Detalle de todas las mermas</h2><p>Costo guardado con cada merma; los registros antiguos sin costo usan el promedio de compras anteriores.</p></div><strong>{dinero(finanzas.perdidas.importe)}<small>{finanzas.perdidas.unidades} flores · {finanzas.perdidas.sinCosto} registros sin costo</small></strong></header><div className="fa-table-scroll"><table className="fa-table"><thead><tr><th>Flor</th><th>Fecha</th><th>Cantidad</th><th>Costo unitario de referencia</th><th>Pérdida</th></tr></thead><tbody>{mermas.clave!==claveMermas?<tr><td colSpan={5}><div className="fa-empty" role="status">Cargando mermas…</div></td></tr>:mermas.error?<tr><td colSpan={5}><div className="fa-empty"><p role="alert">{mermas.error}</p><button className="fa-button secondary" onClick={recargar}>Reintentar</button></div></td></tr>:!detalle?.contenido.length?<tr><td colSpan={5}><div className="fa-empty">No hay mermas para este período.</div></td></tr>:detalle.contenido.map(d=><tr key={d.id}><td data-label="Flor"><strong>{d.nombre}</strong><small className="rp-id">Merma #{d.id}</small></td><td data-label="Fecha">{fechaTexto(d.fecha)}</td><td data-label="Cantidad">{d.cantidad}</td><td data-label="Costo unitario">{d.costoUnitario==null?"Sin costo registrado":dinero(d.costoUnitario)}{d.costoUnitario!=null&&!d.costoRegistrado&&<small> · Estimado</small>}</td><td data-label="Pérdida" className="fa-amount">{d.importe==null?"Sin valorar":dinero(d.importe)}</td></tr>)}</tbody></table></div>
          <footer className="fa-pagination"><label>Mostrar <select aria-label="Mermas por página" value={tamano} onChange={e=>{setTamano(Number(e.target.value));setPagina(0);}}>{[10,20,50].map(n=><option key={n}>{n}</option>)}</select> por página</label><p>{detalle?`${detalle.totalElementos?detalle.pagina*detalle.tamano+1:0}–${Math.min((detalle.pagina+1)*detalle.tamano,detalle.totalElementos)} de ${detalle.totalElementos}`:"…"}</p><nav aria-label="Paginación de mermas del reporte"><button className="fa-icon-button" aria-label="Página anterior" disabled={!detalle||detalle.pagina===0} onClick={()=>setPagina((detalle?.pagina||0)-1)}>←</button><span>{detalle?`${detalle.pagina+1} / ${Math.max(1,detalle.totalPaginas)}`:"…"}</span><button className="fa-icon-button" aria-label="Página siguiente" disabled={!detalle||detalle.pagina+1>=detalle.totalPaginas} onClick={()=>setPagina((detalle?.pagina||0)+1)}>→</button></nav></footer>
        </section>
      </>}
      {seccion==="clientes"&&<div className="rp-grid"><Ranking titulo="Clientes con más pedidos" descripcion="Solicitudes de flores del período, excluyendo las canceladas." datos={operativos.clientesPEDIDOS} columnas={[{campo:"solicitudes",titulo:"Pedidos"}]}/><Ranking titulo="Clientes con más arreglos" descripcion="Ordenados por cantidad de arreglos solicitados; excluye cancelados." datos={operativos.clientesARREGLOS} columnas={[{campo:"unidades",titulo:"Arreglos"},{campo:"solicitudes",titulo:"Pedidos"}]}/><Ranking titulo="Arreglos más solicitados" descripcion="Cantidad de arreglos, aunque un pedido tenga varias unidades. Excluye cancelados." datos={operativos.arreglosSolicitados} columnas={[{campo:"unidades",titulo:"Arreglos"},{campo:"solicitudes",titulo:"Pedidos"}]}/><Ranking titulo="Clientes con más eventos" descripcion="Eventos solicitados para el período, excluyendo cancelados." datos={operativos.clientesEVENTOS} columnas={[{campo:"solicitudes",titulo:"Eventos"}]}/></div>}
      {seccion==="compras"&&<>
        <div className="rp-grid"><Ranking titulo="Flores más compradas a proveedores" descripcion="Cantidad de flores recibidas e importe de sus detalles de compra." datos={operativos.floresCompradas} columnas={[{campo:"unidades",titulo:"Flores"},{campo:"importe",titulo:"Compras"}]}/><Ranking titulo="Proveedores con más compras" descripcion="Ordenados por importe comprado; incluye el número de entradas." datos={operativos.proveedores} columnas={[{campo:"compras",titulo:"Entradas"},{campo:"importe",titulo:"Compras"}]}/></div>
        <section className="fa-list-card rp-gastos"><header className="rp-card-heading"><div><h2>Cuánto se gasta por mes</h2><p>Compras de inventario agrupadas por mes dentro del período seleccionado.</p></div><strong>{dinero(operativos.gastos.importe)}<small>{operativos.gastos.compras} compras</small></strong></header><div className="fa-table-scroll"><table className="fa-table"><thead><tr><th>Mes</th><th>Compras</th><th>Importe</th><th>Distribución del gasto</th></tr></thead><tbody>{operativos.gastosMensuales.map(g=><tr key={g.mes}><td data-label="Mes">{g.mes}</td><td data-label="Compras">{g.compras}</td><td data-label="Importe" className="fa-amount">{dinero(g.importe)}</td><td data-label="Distribución"><div className="rp-bar" role="img" aria-label={`${g.mes}: ${dinero(g.importe)}`}><span style={{width:`${operativos.gastos.importe?g.importe/operativos.gastos.importe*100:0}%`}}/></div></td></tr>)}{!operativos.gastosMensuales.length&&<tr><td colSpan={4}><div className="fa-empty">No hay compras para este período.</div></td></tr>}</tbody></table></div></section>
      </>}
    </>}
  </section>;
}
