import {useEffect,useState} from 'react';
import {api} from '../../../services/apiService';
import {dinero,fechaTexto,mensajeError} from '../../../services/gestionService';
import type {Registro,Pagina,Modulo} from '../../../services/gestionService';
import type {Evento,PaginaEventos} from '../../../types/evento';
import {fechaLocal} from '../../../types/evento';
import type {Comprobante,TipoComprobante} from '../../../types/comprobante';
import {emitirComprobante} from '../../../services/documentosService';
import Modal from '../../../components/shared/Modal';
import SelectorMes from '../../../components/shared/SelectorMes';
const tipos:Record<TipoComprobante,string>={PEDIDO:'Pedido de flores',ARREGLO:'Pedido de arreglos',EVENTO:'Evento',INVENTARIO:'Compra de inventario'};
export default function Emitir({cerrar,emitido}:{cerrar:()=>void;emitido:(c:Comprobante)=>void}){
 const [tipo,setTipo]=useState<TipoComprobante>('PEDIDO'),[mes,setMes]=useState(()=>fechaLocal(new Date()).slice(0,7)),[q,setQ]=useState(''),[pagina,setPagina]=useState(0),[seleccion,setSeleccion]=useState<Registro|null>(null),[ocupado,setOcupado]=useState(false),[error,setError]=useState('');
 const [resultado,setResultado]=useState<{clave:string;filas?:Registro[];paginas?:number;error?:string}>({clave:''});const clave=JSON.stringify([tipo,mes,q,pagina]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{try{let filas:Registro[],paginas:number;if(tipo==='EVENTO'){const [anio,m]=mes.split('-').map(Number);const {data}=await api.get<PaginaEventos>('/evento/pagina',{params:{anio,mes:m,q,pagina,tamano:10},signal:controller.signal});filas=data.contenido.map((e:Evento)=>({id:e.idEvento,nombre:e.nombre,secundario:e.nombreCliente,estado:e.estado,fecha:e.fecha,total:e.importe??undefined}));paginas=data.totalPaginas;}else{const modulo:Modulo=tipo==='PEDIDO'?'pedidos':tipo==='ARREGLO'?'pedidosArreglos':'inventario';const {data}=await api.get<Pagina>(`/gestion/${modulo}/pagina`,{params:{mes,q,pagina,tamano:10},signal:controller.signal});filas=data.contenido;paginas=data.totalPaginas;}if(!controller.signal.aborted)setResultado({clave,filas,paginas});}catch(e){if(!controller.signal.aborted)setResultado({clave,error:mensajeError(e)});}},q?250:0);return()=>{clearTimeout(timer);controller.abort();};},[tipo,mes,q,pagina,clave]);
 const datos=resultado.clave===clave?resultado:undefined;
 return <Modal titulo="Generar comprobante" cerrar={cerrar} ocupado={ocupado}><p className="rc-intro">Selecciona una operación registrada. Al emitir se conservará una copia de sus datos; si ya tiene comprobante, se abrirá el existente.</p>
 <div className="rc-create-filters"><label className="fa-field">Tipo de operación<select className="cp-select" value={tipo} disabled={ocupado} onChange={e=>{setTipo(e.target.value as TipoComprobante);setSeleccion(null);setPagina(0);setError('');}}>{Object.entries(tipos).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="fa-field">Mes de la operación<SelectorMes id="rc-mes-operacion" value={mes} onChange={v=>{setMes(v||fechaLocal(new Date()).slice(0,7));setPagina(0);setSeleccion(null);}}/></label><label className="fa-field">Buscar operación<input maxLength={100} value={q} disabled={ocupado} placeholder="Nombre o número…" onChange={e=>{setQ(e.target.value);setPagina(0);setSeleccion(null);}}/></label></div>
 {error&&<p className="fa-alert" role="alert">{error}</p>}
 {!datos?<p role="status">Consultando operaciones…</p>:datos.error?<p className="fa-alert" role="alert">{datos.error}</p>:!datos.filas?.length?<p className="fa-empty">No hay operaciones en este mes.</p>:<div className="rc-operation-list">{datos.filas.map(r=><button type="button" key={r.id} aria-pressed={seleccion?.id===r.id} disabled={ocupado||r.estado==='CANCELADO'||r.total==null} onClick={()=>{setSeleccion(r);setError('');}}><span><strong>#{r.id} · {r.nombre}</strong><small>{r.secundario} · {fechaTexto(r.fecha)}</small><small>{r.estado==='CANCELADO'?'Cancelado':r.total==null?'Registra el importe antes de emitir':String(r.estado||'Registrado').toLowerCase()}</small></span><strong>{r.total==null?'Sin importe':dinero(r.total)}</strong><i className={`bi bi-${seleccion?.id===r.id?'check-circle-fill':'circle'}`} aria-hidden="true"/></button>)}</div>}
 <nav className="rc-select-pagination" aria-label="Páginas de operaciones"><button className="fa-icon-button" aria-label="Operaciones anteriores" disabled={ocupado||!datos||pagina===0} onClick={()=>{setPagina(p=>p-1);setSeleccion(null);}}>←</button><span>{pagina+1} / {Math.max(1,datos?.paginas||0)}</span><button className="fa-icon-button" aria-label="Operaciones siguientes" disabled={ocupado||!datos||pagina+1>=(datos.paginas||0)} onClick={()=>{setPagina(p=>p+1);setSeleccion(null);}}>→</button></nav>
 <div className="fa-form-actions"><button className="fa-button" disabled={ocupado||!seleccion} onClick={async()=>{if(!seleccion||ocupado)return;setOcupado(true);setError('');try{const c=await emitirComprobante(tipo,seleccion.id);emitido(c);}catch(e){setError(mensajeError(e));}finally{setOcupado(false);}}}><i className="bi bi-receipt" aria-hidden="true"/>{ocupado?'Emitiendo…':'Emitir comprobante'}</button></div></Modal>;
}
