import {useEffect,useState} from 'react';
import {api} from '../../../services/apiService';
import {dinero,fechaTexto,mensajeError} from '../../../services/gestionService';
import type {Comprobante,PaginaComprobantes} from '../../../types/comprobante';
import {numeroComprobante,nombresComprobante} from '../../../types/comprobante';
import {consultarComprobante} from '../../../services/documentosService';
import SelectorMes from '../../../components/shared/SelectorMes';
import Modal from '../../../components/shared/Modal';
import Emitir from './Emitir';
import Documento from './Documento';
export default function IndexRecibos(){
 const [tipo,setTipo]=useState(''),[mes,setMes]=useState(''),[q,setQ]=useState(''),[pagina,setPagina]=useState(0),[tamano,setTamano]=useState(10),[revision,setRevision]=useState(0),[crear,setCrear]=useState(false),[ver,setVer]=useState<Comprobante|null>(null),[ocupado,setOcupado]=useState(false),[error,setError]=useState('');
 const [resultado,setResultado]=useState<{clave:string;data?:PaginaComprobantes;error?:string}>({clave:''}),clave=JSON.stringify([tipo,mes,q,pagina,tamano,revision]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{api.get<PaginaComprobantes>('/comprobante/pagina',{params:{tipo,mes,q,pagina,tamano},signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted)setResultado({clave,data});}).catch(e=>{if(!controller.signal.aborted)setResultado({clave,error:mensajeError(e)});});},q?250:0);return()=>{clearTimeout(timer);controller.abort();};},[tipo,mes,q,pagina,tamano,revision,clave]);
 const data=resultado.clave===clave?resultado.data:undefined;
 const pdf=async(c:Comprobante)=>{if(ocupado)return;setOcupado(true);setError('');try{const {pdfComprobante}=await import('../../../services/exportarDocumentos');await pdfComprobante(c);}catch(e){setError(e instanceof Error?e.message:mensajeError(e));}finally{setOcupado(false);}};
 const abrir=async(id:number,descargar=false)=>{if(ocupado)return;setOcupado(true);setError('');let c:Comprobante;try{c=await consultarComprobante(id);}catch(e){setError(mensajeError(e));setOcupado(false);return;}setOcupado(false);if(descargar)await pdf(c);else setVer(c);};
 return <section className="fa-management rc-page"><header className="fa-page-heading"><div><p className="fa-eyebrow">FlorArte / Documentos</p><h1><i className="bi bi-receipt" aria-hidden="true"/>Recibos y comprobantes</h1><p>Documenta pedidos, arreglos, eventos y compras de inventario con el logo y los datos de FlorArte.</p></div><div className="fa-heading-actions"><button className="fa-button secondary" disabled={ocupado} onClick={()=>setRevision(r=>r+1)}>Actualizar</button><button className="fa-button" disabled={ocupado} onClick={()=>{setCrear(true);setError('');}}>Generar comprobante</button></div></header>
 {error&&<p className="fa-alert" role="alert">{error}</p>}
 <div className="rc-summary"><i className="bi bi-file-earmark-check" aria-hidden="true"/><div><strong>{data?.totalElementos??'…'} documentos emitidos</strong><p>Cada operación tiene un único comprobante. Puedes volver a descargarlo desde este historial.</p></div></div>
 <div className="fa-list-card"><div className="fa-filters"><label className="fa-search">Buscar<input maxLength={100} value={q} placeholder="Cliente, proveedor o número…" onChange={e=>{setQ(e.target.value);setPagina(0);}}/></label><label>Tipo<select value={tipo} onChange={e=>{setTipo(e.target.value);setPagina(0);}}><option value="">Todos</option>{Object.entries(nombresComprobante).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Mes de emisión<SelectorMes id="rc-mes-emision" value={mes} onChange={v=>{setMes(v);setPagina(0);}}/></label></div>
 <div className="fa-table-scroll"><table className="fa-table"><thead><tr><th>Documento</th><th>Cliente / proveedor</th><th>Emitido</th><th>Total</th><th>Acciones</th></tr></thead><tbody>{resultado.clave!==clave?<tr><td colSpan={5}><p className="fa-empty" role="status">Cargando comprobantes…</p></td></tr>:resultado.error?<tr><td colSpan={5}><p className="fa-alert" role="alert">{resultado.error}</p></td></tr>:!data?.contenido.length?<tr><td colSpan={5}><div className="fa-empty"><i className="bi bi-receipt" aria-hidden="true"/><h3>No hay comprobantes para esta consulta</h3><p>Genera uno a partir de una operación registrada.</p></div></td></tr>:data.contenido.map(c=><tr key={c.id}><td data-label="Documento"><strong>{numeroComprobante(c)}</strong><small className="rp-id">{nombresComprobante[c.tipo]} · #{c.idOrigen}</small></td><td data-label="Cliente / proveedor">{c.persona}</td><td data-label="Emitido">{fechaTexto(c.emitidoEn)}</td><td data-label="Total" className="fa-amount">{dinero(c.total)}</td><td data-label="Acciones"><div className="fa-row-actions"><button className="fa-icon-button" disabled={ocupado} aria-label={`Ver comprobante ${c.id}`} onClick={()=>void abrir(c.id)}><i className="bi bi-eye" aria-hidden="true"/></button><button className="fa-icon-button" disabled={ocupado} aria-label={`Descargar PDF ${c.id}`} onClick={()=>void abrir(c.id,true)}><i className="bi bi-file-earmark-pdf" aria-hidden="true"/></button></div></td></tr>)}</tbody></table></div>
 <footer className="fa-pagination"><label>Mostrar<select aria-label="Comprobantes por página" value={tamano} onChange={e=>{setTamano(Number(e.target.value));setPagina(0);}}>{[10,20,50].map(n=><option key={n}>{n}</option>)}</select></label><p>{data?.totalElementos??'…'} resultados</p><nav aria-label="Paginación de comprobantes"><button className="fa-icon-button" aria-label="Comprobantes anteriores" disabled={!data||data.pagina===0} onClick={()=>setPagina((data?.pagina||0)-1)}>←</button><span>{data?`${data.pagina+1} / ${Math.max(1,data.totalPaginas)}`:'…'}</span><button className="fa-icon-button" aria-label="Comprobantes siguientes" disabled={!data||data.pagina+1>=data.totalPaginas} onClick={()=>setPagina((data?.pagina||0)+1)}>→</button></nav></footer></div>
 {crear&&<Emitir cerrar={()=>setCrear(false)} emitido={c=>{setCrear(false);setVer(c);setPagina(0);setTipo('');setMes('');setQ('');setRevision(r=>r+1);}}/>}
 {ver&&<Modal titulo={numeroComprobante(ver)} ocupado={ocupado} cerrar={()=>setVer(null)}><div className="rc-preview-actions"><button className="fa-button" disabled={ocupado} onClick={()=>void pdf(ver)}><i className="bi bi-file-earmark-pdf" aria-hidden="true"/>{ocupado?'Generando PDF…':'Descargar PDF'}</button></div>{error&&<p className="fa-alert" role="alert">{error}</p>}<Documento comprobante={ver}/></Modal>}
 </section>;
}
