import {useEffect,useState} from "react";
import {useNavigate,useParams,useSearchParams} from "react-router-dom";
import {api} from "../../../services/apiService";
import {mensajeError} from "../../../services/gestionService";
import type {Registro} from "../../../services/gestionService";
import type {Evento} from "../../../types/evento";
import type {UserFull} from "../../../types/user";
import CampoNumero from "../../../components/shared/CampoNumero";
import SelectorRegistro from "../../../components/shared/SelectorRegistro";

interface Linea {idFlor:number;nombreFlor:string;cantidad:string}
export default function FormularioEvento({editar=false}:{editar?:boolean}) {
  const {id}=useParams(),navigate=useNavigate(),[params]=useSearchParams();
  const [nombre,setNombre]=useState(""),[fecha,setFecha]=useState(()=>{const dia=params.get("dia");return dia&&/^\d{4}-\d{2}-\d{2}$/.test(dia)?`${dia}T09:00`:"";}),[dias,setDias]=useState("0"),[descripcion,setDescripcion]=useState(""),[ubicacion,setUbicacion]=useState("");
  const [importe,setImporte]=useState("");
  const [cliente,setCliente]=useState<Registro|null>(null),[responsable,setResponsable]=useState<number|null>(null),[nombreResponsable,setNombreResponsable]=useState(""),[terminado,setTerminado]=useState(false),[pagado,setPagado]=useState(false);
  const [detalles,setDetalles]=useState<Linea[]>([]),[flor,setFlor]=useState<Registro|null>(null),[cantidad,setCantidad]=useState("");
  const [cargando,setCargando]=useState(true),[guardando,setGuardando]=useState(false),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();const cargar=async()=>{try{
    if(editar){const {data}=await api.get<Evento>(`/evento/${id}`,{signal:controller.signal});if(controller.signal.aborted)return;setNombre(data.nombre);setImporte(data.importe==null?"":String(data.importe));setFecha(data.fecha.slice(0,16));setDias(String(data.diasPreparacion));setDescripcion(data.descripcion||"");setUbicacion(data.ubicacion||"");setCliente({id:data.idCliente,nombre:data.nombreCliente});setResponsable(data.idEmpleado);setNombreResponsable(data.nombreEmpleado||"Sin asignar");setTerminado(["REALIZADO","PAGADO"].includes(data.estado));setPagado(data.estado==="PAGADO");setDetalles((data.detalles||[]).map(d=>({...d,cantidad:String(d.cantidad)})));}
    else{const sesion=JSON.parse(localStorage.getItem("user")||"{}");const {data}=await api.get<UserFull>(`/user/${sesion.id}`,{signal:controller.signal});if(controller.signal.aborted)return;setResponsable(data.idPersona);setNombreResponsable(data.persona.nombre);}
  }catch(err){if(!controller.signal.aborted)setError(mensajeError(err));}finally{if(!controller.signal.aborted)setCargando(false);}};void cargar();return()=>controller.abort();},[editar,id]);
  const agregar=()=>{if(!flor||!Number.isInteger(Number(cantidad))||Number(cantidad)<=0){setError("Selecciona una flor y una cantidad entera positiva.");return;}if(detalles.some(d=>d.idFlor===flor.id)){setError("Esta flor ya está agregada; modifica su cantidad en la tabla.");return;}if(detalles.length>=200){setError("Puedes registrar hasta 200 flores diferentes.");return;}setDetalles(prev=>[...prev,{idFlor:flor.id,nombreFlor:`${flor.nombre} ${flor.secundario||""}`,cantidad}]);setFlor(null);setCantidad("");setError("");};
  const inicio=fecha&&dias.trim()&&Number.isInteger(Number(dias))?new Date(`${fecha.slice(0,10)}T12:00:00`):null;if(inicio)inicio.setDate(inicio.getDate()-Number(dias));
  return <section className="fa-editor fa-arr-editor"><button className="fa-button tertiary" onClick={()=>navigate("..")}>← Calendario de eventos</button><p className="fa-eyebrow">Agenda de clientes</p><h1>{editar?"Editar evento":"Nuevo evento"}</h1><p>Registra lo necesario, incluso si el evento es lejano. Las flores se apartan cuando confirmas el evento.</p>
    {error&&<p className="fa-alert" role="alert">{error}</p>}{cargando?<p role="status">Cargando datos…</p>:<form onSubmit={async e=>{e.preventDefault();if(guardando)return;setError("");if(!nombre.trim()||!cliente||!fecha||!dias.trim()||!Number.isInteger(Number(dias))||Number(dias)<0||Number(dias)>365||!detalles.length||detalles.some(d=>!d.cantidad.trim()||!Number.isInteger(Number(d.cantidad))||Number(d.cantidad)<=0)){setError("Completa nombre, cliente, fecha, días de preparación y las cantidades de flores.");return;}if(!editar&&!responsable){setError("No se pudo identificar al responsable. Revisa tu sesión.");return;}setGuardando(true);try{const datos={nombre:nombre.trim(),importe:importe.trim()?Number(importe):null,idCliente:cliente.id,idEmpleado:responsable,fecha:fecha.length===16?`${fecha}:00`:fecha,diasPreparacion:Number(dias),descripcion:descripcion.trim()||null,ubicacion:ubicacion.trim()||null,detalles:detalles.map(d=>({idFlor:d.idFlor,cantidad:Number(d.cantidad)}))};if(editar)await api.put(`/evento/update/${id}`,datos);else await api.post("/evento/create",datos);navigate("..");}catch(err){setError(mensajeError(err));}finally{setGuardando(false);}}}>
      <fieldset className="fa-fieldset" disabled={guardando}><div className="fa-arr-fields"><label className="fa-field" htmlFor="evento-nombre">Nombre *<input id="evento-nombre" required maxLength={150} value={nombre} onChange={e=>setNombre(e.target.value)}/></label><SelectorRegistro modulo="personas" rol="CLIENTE" label="Cliente" nombre={cliente?.nombre||""} onSelect={setCliente}/><label className="fa-field" htmlFor="evento-fecha">Fecha y hora del evento *<input id="evento-fecha" type="datetime-local" required min="1900-01-01T00:00" max="9999-12-31T23:59" value={fecha} onChange={e=>setFecha(e.target.value)}/></label><label className="fa-field" htmlFor="evento-dias">Días de preparación antes del evento *<CampoNumero id="evento-dias" required min="0" max="365" step="1" value={dias} onChange={e=>setDias(e.target.value)}/></label><label className="fa-field" htmlFor="evento-importe">Importe acordado (Q){pagado?" *":" (opcional)"}<CampoNumero id="evento-importe" required={pagado} min="0" max="99999999.99" step="0.01" value={importe} onChange={e=>setImporte(e.target.value)}/><small>Necesario para registrar el pago y sus ingresos en reportes.</small></label><label className="fa-field fa-full" htmlFor="evento-ubicacion">Ubicación (opcional)<input id="evento-ubicacion" maxLength={250} value={ubicacion} onChange={e=>setUbicacion(e.target.value)}/></label><label className="fa-field fa-full" htmlFor="evento-descripcion">Descripción (opcional)<textarea id="evento-descripcion" className="cp-input" maxLength={5000} rows={3} value={descripcion} onChange={e=>setDescripcion(e.target.value)}/></label></div>
      <p className="fa-edit-notice">Responsable: {nombreResponsable||"Sin asignar"}. {inicio&&!Number.isNaN(inicio.getTime())?`Preparación desde el ${inicio.toLocaleDateString("es-GT")}.`:"Selecciona la fecha para calcular el inicio de preparación."}</p>
      <div className="fa-section-label"><h2>Flores necesarias</h2><span>{detalles.length} flores diferentes</span></div>
      {terminado?<p className="fa-edit-notice">Las flores ya fueron utilizadas. Puedes corregir los datos del evento, pero su composición se conserva.</p>:<div className="fa-arr-add"><SelectorRegistro modulo="flores" estado="activa" label="Flor" nombre={flor?`${flor.nombre} ${flor.secundario||""}`:""} onSelect={setFlor}/><label className="fa-field" htmlFor="evento-cantidad">Cantidad de flores<CampoNumero id="evento-cantidad" min="1" max="2147483647" step="1" value={cantidad} onChange={e=>setCantidad(e.target.value)}/></label><button type="button" className="fa-button secondary" onClick={agregar}>Agregar flor</button></div>}
      <div className="fa-table-scroll"><table className="fa-table"><thead><tr><th>Flor</th><th>Cantidad</th><th>Acciones</th></tr></thead><tbody>{detalles.map(d=><tr key={d.idFlor}><td>{d.nombreFlor}</td><td><CampoNumero required disabled={terminado} aria-label={`Cantidad de ${d.nombreFlor}`} className="cp-input fa-quantity" min="1" max="2147483647" step="1" value={d.cantidad} onChange={e=>setDetalles(prev=>prev.map(linea=>linea.idFlor===d.idFlor?{...linea,cantidad:e.target.value}:linea))}/></td><td><button type="button" className="fa-icon-button danger" disabled={terminado} aria-label={`Quitar ${d.nombreFlor}`} onClick={()=>setDetalles(prev=>prev.filter(linea=>linea.idFlor!==d.idFlor))}><i className="bi bi-trash3" aria-hidden="true"/></button></td></tr>)}{!detalles.length&&<tr><td colSpan={3}>Agrega las flores que necesitará el evento.</td></tr>}</tbody></table></div>
      <div className="fa-form-actions"><button type="button" className="fa-button secondary" onClick={()=>navigate("..")}>Cancelar</button><button className="fa-button">{guardando?"Guardando…":"Guardar evento"}</button></div></fieldset>
    </form>}
  </section>;
}
