import {useEffect,useId,useState} from "react";
import {useNavigate} from "react-router-dom";
import {api} from "../../../services/apiService";
import {fechaTexto,mensajeError} from "../../../services/gestionService";
import {estadosEvento,fechaLocal,reservaTexto} from "../../../types/evento";
import type {Evento,PaginaEventos,CalendarioEventos} from "../../../types/evento";
import SelectorMes from "../../../components/shared/SelectorMes";
import Modal from "../../../components/shared/Modal";
import {nombrePeriodo} from "../../../utils/periodo";
import DetalleEvento from "./Detalle";

export default function IndexEventos() {
  const navigate=useNavigate(),id=useId(),admin=localStorage.getItem("role")==="ADMINISTRADOR";
  const [mes,setMes]=useState(()=>fechaLocal(new Date()).slice(0,7)),[dia,setDia]=useState(""),[periodo,setPeriodo]=useState("mes"),[preparacion,setPreparacion]=useState(false),[estado,setEstado]=useState(""),[q,setQ]=useState(""),[busqueda,setBusqueda]=useState("");
  const [pagina,setPagina]=useState(0),[tamano,setTamano]=useState(10),[revision,setRevision]=useState(0);
  const [resultado,setResultado]=useState<{clave:string;data?:PaginaEventos;error?:string}>({clave:""}),[calendario,setCalendario]=useState<{clave:string;data?:CalendarioEventos;error?:string}>({clave:""});
  const [ver,setVer]=useState<number|null>(null),[eliminar,setEliminar]=useState<Evento|null>(null),[ocupado,setOcupado]=useState(false),[errorOperacion,setErrorOperacion]=useState(""),[ahora,setAhora]=useState(Date.now),[desfase,setDesfase]=useState(0);
  const anio=Number(mes.slice(0,4)),numeroMes=Number(mes.slice(5,7));
  const clave=JSON.stringify([mes,dia,periodo,preparacion,estado,busqueda,pagina,tamano,revision]),claveCalendario=JSON.stringify([mes,estado,busqueda,revision]);
  useEffect(()=>{const timer=setTimeout(()=>setBusqueda(q),250);return()=>clearTimeout(timer);},[q]);
  useEffect(()=>{const timer=setInterval(()=>setAhora(Date.now()),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{const controller=new AbortController();api.get<PaginaEventos>("/evento/pagina",{params:{anio,mes:periodo==="anio"?0:numeroMes,dia:periodo==="dia"?dia:"",preparacion,estado,q:busqueda,pagina,tamano},signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted){setResultado({clave,data});setDesfase(new Date(data.horaServidor).getTime()-Date.now());}}).catch(err=>{if(!controller.signal.aborted)setResultado({clave,error:mensajeError(err)});});return()=>controller.abort();},[anio,numeroMes,dia,periodo,preparacion,estado,busqueda,pagina,tamano,revision,clave]);
  useEffect(()=>{const controller=new AbortController();api.get<CalendarioEventos>("/evento/calendario",{params:{anio,mes:numeroMes,estado,q:busqueda},signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted)setCalendario({clave:claveCalendario,data});}).catch(err=>{if(!controller.signal.aborted)setCalendario({clave:claveCalendario,error:mensajeError(err)});});return()=>controller.abort();},[anio,numeroMes,estado,busqueda,revision,claveCalendario]);
  const data=resultado.clave===clave?resultado.data:undefined,cargando=resultado.clave!==clave;
  const cal=calendario.clave===claveCalendario?calendario.data:undefined;
  const recargar=()=>setRevision(r=>r+1);
  const editable=(e:Evento)=>admin||e.puedeEditar&&ahora+desfase<new Date(e.editableHasta).getTime();
  const elegirMes=(value:string)=>{setMes(value||fechaLocal(new Date()).slice(0,7));setDia("");setPeriodo("mes");setPagina(0);};
  const mover=(delta:number)=>{const date=new Date(anio,numeroMes-1+delta,1);if(date.getFullYear()>=1900&&date.getFullYear()<=9999)elegirMes(fechaLocal(date).slice(0,7));};
  const elegirDia=(value:string,preparar=false)=>{setDia(value);setPeriodo("dia");setPreparacion(preparar);setPagina(0);};
  const inicio=(new Date(anio,numeroMes-1,1).getDay()+6)%7,totalDias=new Date(anio,numeroMes,0).getDate(),hoy=fechaLocal(new Date());
  const celdas=Array.from({length:Math.ceil((inicio+totalDias)/7)*7},(_,i)=>i-inicio+1);
  return <section className="fa-management ev-page" aria-labelledby={`${id}-titulo`}>
    <header className="fa-page-heading"><div><p className="fa-eyebrow">FlorArte / Agenda de clientes</p><h1 id={`${id}-titulo`}><i className="bi bi-calendar2-week" aria-hidden="true"/>Calendario de eventos</h1><p>Planifica la preparación, consulta tus próximas fechas y controla las flores comprometidas.</p></div><button className="fa-button" onClick={()=>navigate(`create${dia?`?dia=${dia}`:""}`)}><i className="bi bi-plus-lg" aria-hidden="true"/>Nuevo evento</button></header>
    <div className="fa-list-card ev-filters"><div className="fa-filters"><label className="fa-search" htmlFor={`${id}-q`}>Buscar<input id={`${id}-q`} maxLength={100} value={q} onChange={e=>{setQ(e.target.value);setPagina(0);}} placeholder="Evento, cliente o ubicación…"/></label><label htmlFor={`${id}-mes`}>Mes y año<SelectorMes id={`${id}-mes`} value={mes} onChange={elegirMes}/></label><label htmlFor={`${id}-periodo`}>Período de la agenda<select id={`${id}-periodo`} value={periodo} onChange={e=>{setPeriodo(e.target.value);if(e.target.value==="dia"&&!dia)setDia(`${mes}-01`);setPagina(0);}}><option value="mes">Mes seleccionado</option><option value="anio">Año completo: {anio}</option><option value="dia">Día seleccionado</option></select></label><label htmlFor={`${id}-dia`}>Día<input id={`${id}-dia`} type="date" min={`${mes}-01`} max={`${mes}-${totalDias}`} value={dia} onChange={e=>{if(e.target.value)elegirDia(e.target.value,preparacion);else{setDia("");setPeriodo("mes");setPagina(0);}}}/></label><label htmlFor={`${id}-estado`}>Estado<select id={`${id}-estado`} value={estado} onChange={e=>{setEstado(e.target.value);setPagina(0);}}><option value="">Todos los estados</option>{estadosEvento.map(e=><option key={e} value={e}>{e.toLowerCase()}</option>)}</select></label><label htmlFor={`${id}-criterio`}>Consultar fechas de<select id={`${id}-criterio`} value={preparacion?"preparacion":"evento"} onChange={e=>{setPreparacion(e.target.value==="preparacion");setPagina(0);}}><option value="evento">Celebración del evento</option><option value="preparacion">Inicio de preparación</option></select></label><button className="fa-button tertiary" onClick={()=>{elegirMes(fechaLocal(new Date()).slice(0,7));setQ("");setEstado("");setPreparacion(false);}}>Hoy / Limpiar filtros</button></div></div>
    <div className="fa-metrics" aria-busy={cargando}><div><span>Eventos del filtro</span><strong>{cargando?"…":data?.resumen.eventos??"—"}</strong><small>{periodo==="anio"?`Año ${anio}`:periodo==="dia"?dia:nombrePeriodo(mes)}</small></div><div><span>Solicitudes pendientes</span><strong>{cargando?"…":data?.resumen.pendientes??"—"}</strong><small>Necesidad registrada, sin descontar stock</small></div><div><span>Flores comprometidas</span><strong>{cargando?"…":data?.resumen.floresReservadas??"—"}</strong><small>En {data?.resumen.reservados??0} eventos confirmados o trabajando</small></div><div className="fa-metric-note"><i className="bi bi-calendar-check" aria-hidden="true"/><span>Reserva al confirmar</span><small>{admin?"Administración y seguimiento":"Editar/eliminar: 30 minutos. Estado sin límite temporal."}</small></div></div>
    <section className="fa-list-card ev-calendar" aria-label="Calendario mensual"><header className="ev-calendar-heading"><h2>{nombrePeriodo(mes)}</h2><div><button className="fa-icon-button" aria-label="Mes anterior" disabled={mes==="1900-01"} onClick={()=>mover(-1)}><i className="bi bi-chevron-left" aria-hidden="true"/></button><button className="fa-icon-button" aria-label="Mes siguiente" disabled={mes==="9999-12"} onClick={()=>mover(1)}><i className="bi bi-chevron-right" aria-hidden="true"/></button></div></header>
      <p className="ev-calendar-help">Selecciona un día para consultar los eventos y sus flores. «Preparar» muestra los eventos cuya preparación comienza ese día.</p>
      {calendario.clave===claveCalendario&&calendario.error?<div className="fa-empty"><p role="alert">{calendario.error}</p><button className="fa-button secondary" onClick={recargar}>Reintentar</button></div>:<div className="ev-calendar-grid" aria-busy={!cal}>
        {["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(d=><div className="ev-weekday" key={d}>{d}</div>)}
        {celdas.map((n,i)=>{if(n<1||n>totalDias)return <div key={`vacio-${i}`} className="ev-day ev-day-empty"/>;const fecha=`${mes}-${String(n).padStart(2,"0")}`,resumen=cal?.dias.find(d=>d.dia===fecha),preparar=cal?.preparacion.find(d=>d.dia===fecha);return <div key={fecha} className={`ev-day ${fecha===hoy?"today":""} ${dia===fecha&&periodo==="dia"?"selected":""} ${resumen?.reservados?"reserved":""}`}><button className="ev-day-main" aria-label={`${fecha}: ${resumen?.eventos??0} eventos`} aria-pressed={dia===fecha&&periodo==="dia"&&!preparacion} onClick={()=>elegirDia(fecha)}><strong>{n}</strong><span>{!cal?"…":resumen?`${resumen.eventos} ${resumen.eventos===1?"evento":"eventos"}`:"Sin eventos"}</span>{!!resumen?.reservados&&<small>{resumen.floresReservadas} flores reservadas</small>}{!!resumen?.pendientes&&<small>{resumen.pendientes} pendientes</small>}{!!resumen?.cancelados&&<small>{resumen.cancelados} cancelados</small>}</button>{preparar&&<button className="ev-prepare" aria-label={`Preparar ${fecha}: ${preparar.eventos} eventos`} onClick={()=>elegirDia(fecha,true)}>Preparar · {preparar.eventos}</button>}</div>;})}
      </div>}
      <footer className="ev-legend"><span><i className="ev-dot reserved"/>Flores reservadas</span><span><i className="ev-dot prepare"/>Inicio de preparación</span><span>Sin eventos = sin registros para estos filtros; pueden coincidir varios eventos.</span></footer>
    </section>
    <section className="fa-list-card ev-agenda" aria-label="Agenda de eventos"><header className="ev-calendar-heading"><div><h2>{preparacion?"Preparaciones programadas":"Agenda de eventos"}</h2><p>{periodo==="dia"?`Día ${dia}`:periodo==="anio"?`Año ${anio}`:nombrePeriodo(mes)}</p></div>{periodo==="dia"&&<button className="fa-button secondary" onClick={()=>{setPeriodo("mes");setDia("");setPagina(0);}}>Ver todo el mes</button>}</header>
      <div className="fa-table-scroll"><table className="fa-table"><thead><tr><th>Evento / Cliente</th><th>Evento y preparación</th><th>Estado</th><th>Flores</th><th>Acciones</th></tr></thead><tbody>{cargando?<tr><td colSpan={5}><div className="fa-empty" role="status">Cargando agenda…</div></td></tr>:resultado.error?<tr><td colSpan={5}><div className="fa-empty"><p role="alert">{resultado.error}</p><button className="fa-button secondary" onClick={recargar}>Reintentar</button></div></td></tr>:!data?.contenido.length?<tr><td colSpan={5}><div className="fa-empty"><i className="bi bi-calendar2" aria-hidden="true"/><h3>Sin eventos registrados</h3><p>Selecciona otro período o registra un evento para este cliente.</p></div></td></tr>:data.contenido.map(e=><tr key={e.idEvento}><td data-label="Evento / Cliente"><div className="fa-record"><span className="fa-record-icon"><i className="bi bi-calendar-event" aria-hidden="true"/></span><div><strong>{e.nombre}</strong><small>#{e.idEvento} · {e.nombreCliente}</small><small>{e.ubicacion}</small></div></div></td><td data-label="Fechas"><div className="fa-contact">{fechaTexto(e.fecha)}<small>Preparar: {e.inicioPreparacion} · {e.diasPreparacion} días antes</small></div></td><td data-label="Estado"><span className={`fa-badge ev-status-${e.estado.toLowerCase()}`}>{e.estado.toLowerCase()}</span></td><td data-label="Flores"><div className="fa-contact">{e.totalFlores} flores<small>{reservaTexto(e)}</small></div></td><td data-label="Acciones"><div className="fa-row-actions"><button className="fa-icon-button" aria-label={`Ver evento ${e.idEvento}`} onClick={()=>setVer(e.idEvento)}><i className="bi bi-eye" aria-hidden="true"/></button><button className="fa-icon-button" disabled={!editable(e)} title={editable(e)?"Editar":"Plazo de edición terminado"} aria-label={`Editar evento ${e.idEvento}`} onClick={()=>navigate(`update/${e.idEvento}`)}><i className="bi bi-pencil-square" aria-hidden="true"/></button><button className="fa-button secondary fa-state-button" disabled={!e.estadosPermitidos.length} aria-label={`Cambiar estado evento ${e.idEvento}`} onClick={()=>setVer(e.idEvento)}>Estado</button><button className="fa-icon-button danger" disabled={!editable(e)||["REALIZADO","PAGADO"].includes(e.estado)} aria-label={`Eliminar evento ${e.idEvento}`} title={["REALIZADO","PAGADO"].includes(e.estado)?"Se conserva en el historial":"Eliminar"} onClick={()=>{setEliminar(e);setErrorOperacion("");}}><i className="bi bi-trash3" aria-hidden="true"/></button></div></td></tr>)}</tbody></table></div>
      <footer className="fa-pagination"><label htmlFor={`${id}-tamano`}>Mostrar <select id={`${id}-tamano`} value={tamano} onChange={e=>{setTamano(Number(e.target.value));setPagina(0);}}>{[10,20,50].map(n=><option key={n}>{n}</option>)}</select> por página</label><p aria-live="polite">{data?`${data.totalElementos?data.pagina*data.tamano+1:0}–${Math.min((data.pagina+1)*data.tamano,data.totalElementos)} de ${data.totalElementos}`:"…"}</p><nav aria-label="Paginación de eventos"><button className="fa-icon-button" aria-label="Página anterior" disabled={!data||data.pagina===0||cargando} onClick={()=>setPagina((data?.pagina||0)-1)}>←</button><span>{data?`${data.pagina+1} / ${Math.max(1,data.totalPaginas)}`:"…"}</span><button className="fa-icon-button" aria-label="Página siguiente" disabled={!data||data.pagina+1>=data.totalPaginas||cargando} onClick={()=>setPagina((data?.pagina||0)+1)}>→</button></nav></footer>
    </section>
    {ver!==null&&<DetalleEvento key={ver} id={ver} cerrar={()=>setVer(null)} guardado={recargar}/>}
    {eliminar&&<Modal titulo={`Eliminar evento #${eliminar.idEvento}`} cerrar={()=>setEliminar(null)} ocupado={ocupado}><div className="fa-confirm"><h3>{eliminar.nombre}</h3><p>{eliminar.reservaAplicada?"Se devolverán las flores reservadas al inventario.":"Se eliminará esta solicitud del calendario."}</p>{errorOperacion&&<p className="fa-alert" role="alert">{errorOperacion}</p>}{!editable(eliminar)&&<p className="fa-alert">El plazo de eliminación terminó.</p>}<button className="fa-button danger" disabled={ocupado||!editable(eliminar)} onClick={async()=>{if(ocupado||!editable(eliminar))return;setOcupado(true);setErrorOperacion("");try{await api.delete(`/evento/delete/${eliminar.idEvento}`);setEliminar(null);recargar();}catch(err){setErrorOperacion(mensajeError(err));}finally{setOcupado(false);}}}>{ocupado?"Eliminando…":"Confirmar eliminación"}</button></div></Modal>}
  </section>;
}
